# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('formula', models.CharField(max_length=500)),
                ('cas_no', models.CharField(max_length=50)),
                ('mol_wt', models.CharField(max_length=50)),
                ('tc', models.CharField(max_length=50)),
                ('pc', models.CharField(max_length=50)),
                ('vc', models.CharField(max_length=50)),
                ('zc', models.CharField(max_length=50)),
                ('af', models.CharField(max_length=50)),
            ],
        ),
    ]
